# Generated by Django 4.2.11 on 2024-04-20 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf_cnpj', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('total_area_hectares', models.FloatField()),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.producer')),
            ],
        ),
        migrations.CreateModel(
            name='AreaFarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_type', models.CharField(choices=[('AR', 'Arable'), ('VE', 'Vegetation')], max_length=2)),
                ('area_hectares', models.FloatField()),
                ('crops', models.CharField(choices=[('SO', 'Soja'), ('MI', 'Milho'), ('AL', 'Algodão'), ('CA', 'Café'), ('CS', 'Cana de Açucar')], max_length=2)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.farm')),
            ],
        ),
    ]
